apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-app
  labels:
    app: monitoring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitoring-app
  template:
    metadata:
      labels:
        app: monitoring-app
    spec:
      containers:
      - name: monitoring-app
        image: sachinbisht577/monitoring-app:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
